opcalendar/urls.py
from django.urls import path

from . import views

app_name = "opcalendar"
urlpatterns = [
    path("index", views.index, name="index"),
    path("", views.CalendarView.as_view(), name="calendar"),
    path("event/new/", views.create_event, name="event_new"),
    path("add_ingame_calendar/", views.add_ingame_calendar, name="add_ingame_calendar"),
    path("event/edit/<int:event_id>/", views.EventEdit, name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "ingame/event/<int:event_id>/details/",
        views.ingame_event_details,
        name="ingame-event-detail",
    ),
    path(
        "add_eventmember/<int:event_id>",
        views.EventMemberSignup,
        name="event_member_signup",
    ),
    path("event/<int:event_id>/remove", views.EventDeleteView, name="remove_event"),
    path(
        "remove_eventmember/<int:event_id>",
        views.EventMemberRemove,
        name="event_member_remove",
    ),
    path("feed.ics", views.EventFeed()),
    path(
        "event/<int:event_id>/details/feed.ics",
        views.EventIcalView(),
        name="event-ical-view",
    ),
    path("event/new/ajax/get_category/", views.get_category, name="get_category"),
    path(
        "event/<int:event_id>/signup/attending/",
        views.event_member_signup_attending,
        name="event_member_signup_attending",
    ),
    path(
        "event/<int:event_id>/signup/maybe/",
        views.event_member_signup_maybe,
        name="event_member_signup_maybe",
    ),
    path(
        "event/<int:event_id>/signup/declined/",
        views.event_member_signup_declined,
        name="event_member_signup_declined",
    ),
    path(
        "event/<int:event_id>/remove/",
        views.event_member_remove,
        name="event_member_remove",
    ),
    path("user/settings/", views.user_settings_view, name="user_settings"),
]

opcalendar/templates/opcalendar/partials/event_details/details.html
{% load i18n %}
<table>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Type:" %}</b></td>
        <td><span class="event {{ event.get_category_class }}">{{ event.operation_type }}</span></td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Availability:" %}</b></td>
        <td><span class="event {{ event.get_visibility_class }}">{{ event.event_visibility }}</span></td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Start time:" %}</b></td>
        <td>{{ event.start_time|date:"D Y-m-d H:i" }} (EVE) / <span id="localtime{{ event.id }}"></span> (Local)</td>
    </tr>

    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Est. end time:" %}</b></td>
        <td>{{ event.end_time|date:"D Y-m-d H:i" }}</td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Duration:" %}</b></td>
        <td>{{ event.duration }}</td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Formup location:" %}</b></td>
        <td>{{ event.formup_system }}</td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Doctrine:" %}</b></td>
        <td>{{ event.doctrine }}</td>
    </tr>
    <tr>
        <td style="padding-right: 10px;"><b>{% trans "Fleet Commander:" %}</b></td>
        <td>{{ event.fc }}</td>
    </tr>
</table>
<br>
{{ event.description|linebreaksbr }}

opcalendar/templates/opcalendar/partials/event_details/host.html
{% load i18n %}

<table>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Community:" %}</b></td>
    <td><span>{{ event.host.community|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Ingame channel:" %}</b></td>
    <td><span>{{ event.host.ingame_channel|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Ingame mailing list:" %}</b></td>
    <td><span>{{ event.host.ingame_mailing_list|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Fleet comms:" %}</b></td>
    <td><span>{{ event.host.fleet_comms|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Fleet doctrines:" %}</b></td>
    <td><span>{{ event.host.fleet_doctrines|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Website:" %}</b></td>
    <td><span>{{ event.host.website|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Discord:" %}</b></td>
    <td><span>{{ event.host.discord|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Twitch:" %}</b></td>
    <td><span>{{ event.host.twitch|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Twitter:" %}</b></td>
    <td><span>{{ event.host.twitter|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Youtube:" %}</b></td>
    <td><span>{{ event.host.youtube|urlize }}</span></td>
</tr>
<tr>
    <td style="padding-right: 10px;"><b>{% trans "Facebook:" %}</b></td>
    <td><span>{{ event.host.facebook|urlize }}</span></td>
</tr>
</table>

opcalendar/templates/opcalendar/partials/event_details/navigation.html
{% load i18n %}

<div class="d-grid gap-2 d-md-flex justify-content-md-start w-100">
    <form method="get" action="{% url 'opcalendar:calendar' %}" class="d-inline">
        <button class="btn btn-primary me-md-2" type="submit"><i class="far fa-calendar-alt"></i> {% trans "Back to Calendar" %}</button>
    </form>
    <form method="get" action="{% url 'opcalendar:event-ical-view' event.pk %}" class="d-inline">
        <button class="btn btn-success me-md-2" type="submit"><i class="fas fa-bookmark"></i> {% trans "Add to my calendar" %}</button>
    </form>
    {% if perms.opcalendar.create_event %}
        {% if not event.external %}
            <form method="get" action="{% url 'opcalendar:event_edit' event.pk %}" class="d-inline">
                <button class="btn btn-primary me-md-2" type="submit"><i class="fas fa-edit"></i> {% trans "Edit Event" %}</button>
            </form>
            <form method="post" action="{% url 'opcalendar:remove_event' event.id %}" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit"><i class="fas fa-trash"></i> {% trans "Remove" %}</button>
            </form>
        {% endif %}
    {% endif %}
</div>

opcalendar/templates/opcalendar/partials/event_details/signups.html
{% load i18n %}

{% if perms.opcalendar.see_signups %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 10px">{% trans "#" %}</th>
        <th>{% trans "Main Character" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Comment" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for member in eventmember %}
      <tr role="row">
          <td>{{ forloop.counter }}</td>
          <td>{{ member.character }}</td>
          <td>
            {% if member.status == "A" %}
              {% trans "Attending" %}
            {% elif member.status == "M" %}
              {% trans "Maybe" %}
            {% elif member.status == "D" %}
              {% trans "Declined" %}
            {% else %}
              {% trans "Unknown" %}
            {% endif %}
          </td>
          <td>{{ member.comment|default:"-" }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

opcalendar/templates/opcalendar/partials/event_details/signups_navigation.html
{% load i18n %}

<div class="d-grid gap-2 d-md-flex justify-content-md-start align-items-center w-100">
    <form method="post" action="{% url 'opcalendar:event_member_signup_attending' event.id %}" class="d-inline" id="attendingForm">
        {% csrf_token %}
        <input type="hidden" name="status" value="A">
        <button class="btn btn-success me-md-2" type="submit"><i class="fa-solid fa-check"></i> {% trans "Attending" %}</button>
    </form>

    <form method="post" action="{% url 'opcalendar:event_member_signup_maybe' event.id %}" class="d-inline" id="maybeForm">
        {% csrf_token %}
        <input type="hidden" name="status" value="M">
        <button class="btn btn-warning me-md-2" type="submit"><i class="fa-solid fa-question"></i> {% trans "Maybe" %}</button>
    </form>

    <form method="post" action="{% url 'opcalendar:event_member_signup_declined' event.id %}" class="d-inline" id="declinedForm">
        {% csrf_token %}
        <input type="hidden" name="status" value="D">
        <button class="btn btn-secondary me-md-2" type="submit"><i class="fa-solid fa-hand"></i> {% trans "Declined" %}</button>
    </form>

    {% if request.user.profile.main_character.character_name in memberlist %}
        <form method="post" action="{% url 'opcalendar:event_member_remove' event.id %}" class="d-inline" id="removeForm">
            {% csrf_token %}
            <button class="btn btn-danger me-md-2" type="submit"><i class="fa-solid fa-trash"></i> {% trans "Remove my event signup" %}</button>
        </form>
    {% endif %}

    <input type="text" name="comment" class="ml-auto comment-input" placeholder="{% trans 'Optional comment' %}" maxlength="100" form="attendingForm">
</div>